ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from noticias import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    #General
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contacto/', views.contact, name='contact'),
    #Noticias
    path('noticias/', views.noticias, name='noticias'),
    path('noticias/detalle/<int:pk>', views.noticia_detalles, name='noticia_detalles'),
    path('noticias/crear', views.crear_noticia, name='crear_noticia'),
    path('noticias/editar/<int:pk>', views.noticia_editar, name='noticia_editar'),
    path('noticias/borrar/<int:pk>', views.borrar_noticia, name='borrar_noticia'),
    #Usuarios
    path('singup/', views.singup, name='singup'),
    path('logout/', views.cerrar_sesion, name='logout'),
    path('singin/', views.abrir_sesion, name='singin'),
    #Comentarios
    path('Comentarios/', include('comentarios.urls')),
] 
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comentarios/urls.py
from django.urls import path
from . import views

app_name = 'comentarios'

urlpatterns = [
    path('agregar/<int:pk>', views.agregar_comentario, name='agregar'),
    path('Borrar/<int:comentario_id>', views.borrar_comentario, name='borrar_comentario'),
    path('Modificar/<int:comentario_id>', views.modificar_comentario, name='modificar_comentario'),
]

noticias/models.py
from django.db import models
from django.contrib.auth.models import User

class Noticia(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True)
    imagen = models.ImageField(upload_to='noticias/', blank=True)  
    fecha = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo + '-hecho por: ' + self.user.username

noticias/forms.py
from django import forms
from .models import Noticia
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NoticiaForm(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = ['titulo', 'descripcion', 'imagen']  # Agrega 'imagen' a los campos del formulario
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
            'imagen': forms.FileInput(attrs={'class': 'form-control'})  # Widget para el campo de imagen
        }


class CustomUserCreationForm(UserCreationForm):
    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if not password1 or not password2:
            raise forms.ValidationError("Los campos de contraseña son obligatorios.")

        return cleaned_data

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields

noticias/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse
from django.db import IntegrityError
from .forms import NoticiaForm
from .models import Noticia
from comentarios.models import Comentario
from django.core.mail import send_mail
from .forms import CustomUserCreationForm

def home(request):
    ultimas_noticias = Noticia.objects.order_by('-fecha')[:3]
    return render(request, 'home.html', {'ultimas_noticias': ultimas_noticias})


def singup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  
            return redirect('noticias')  
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'singup.html', {'form': form})
        
def noticias(request):
    noticias = Noticia.objects.all()
    return render(request, 'noticias.html', {'noticias': noticias})


def cerrar_sesion(request):
    logout(request)
    return redirect('home')

def abrir_sesion(request):
    if request.method == 'GET':
        return render(request, 'singin.html',{
            'form': AuthenticationForm
        })
    else: 
        user = authenticate(
            request, username=request.POST['username'], password=request.POST
            ['password'])
        if user is None:
            return render(request, 'singin.html',{
            'form': AuthenticationForm,
            "error": 'Usuario o contraseña incorrecto'
        })
        else:
            login(request, user)
            return redirect ('noticias')

def crear_noticia(request):
    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES)
        if form.is_valid():
            nueva_noticia = form.save(commit=False)
            nueva_noticia.user = request.user
            # Guardar la imagen asociada a la noticia
            if 'imagen' in request.FILES:
                nueva_noticia.imagen = request.FILES['imagen']
            nueva_noticia.save()
            return redirect('noticias')
        else:
            # Manejar el caso cuando el formulario no es válido
            return render(request, 'crear_noticia.html', {'form': form, 'error': 'Ingresa datos válidos'})
    else:
        form = NoticiaForm()
    return render(request, 'crear_noticia.html', {'form': form})

def noticia_editar(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk, user=request.user)

    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES, instance=noticia)
        if form.is_valid():
            form.save()
            return redirect('noticias')
    else:
        form = NoticiaForm(instance=noticia)

    return render(request, 'noticia_editar.html', {'noticia': noticia, 'form': form})
         
def borrar_noticia(request, pk):
    noticia = get_object_or_404(Noticia, pk= pk, user= request.user)
    if request.method == 'POST':
        noticia.delete()
        return redirect('noticias')

def noticia_detalles(request, pk):
    noticia = get_object_or_404(Noticia, pk=pk)
    comentarios = Comentario.objects.filter(noticia=noticia)

    ctx = {'noticia': noticia, 'comentarios': comentarios}
    return render(request, 'noticia_detalles.html', ctx)

def about(request):
    return render(request, 'about.html')

def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        send_mail(
            f'Mensaje de {name}',
            f'Email: {email}\nTeléfono: {phone}\n\nMensaje: {message}',
            email,  # Desde
            ['lautaromoreyra144@gmail.com'],  # A
            fail_silently=False,
        )
        return render(request, 'contact.html', {'success': True})  # Puedes enviar una confirmación

    return render(request, 'contact.html')  # Si es un GET, solo muestra la página de contacto

noticias/templates/about.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
    <!-- Main Content -->
    <main class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7 text-center mt-5"> <!-- Agregamos 'mt-5' para más espacio superior -->
                    <p class="mb-4"> <!-- Agregamos un espacio inferior para separar los párrafos -->
                        En Chaco Innova, nos dedicamos a resaltar y apoyar a los emprendedores en el Chaco, Argentina. Queremos ser un lugar donde las personas con ideas nuevas puedan conectar, aprender y crecer.
                    </p>
                    <p class="mb-4"> <!-- Agregamos un espacio inferior para separar los párrafos -->
                        Nos esforzamos por presentar una amplia gama de emprendimientos locales, desde pequeños negocios hasta proyectos ambiciosos, así como destinos turísticos únicos y experiencias enriquecedoras que pueden ser disfrutadas a lo largo y ancho de nuestra provincia. 
                    </p>
                    <p> <!-- Eliminamos el espacio inferior del último párrafo -->
                        ¡Te invitamos a sumergirte en nuestras noticias, a explorar las historias que destacan el espíritu emprendedor del Chaco y a descubrir los destinos turísticos y emprendimientos que enriquecen nuestra provincia!
                    </p>
                </div>
            </div>
        </div>
    </main>
    <!-- Footer -->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <!-- Los elementos del footer permanecen sin cambios -->
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS -->
    <script src="{% static 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Core theme JS -->
    <script src="{% static 'js/scripts.js' %}"></script>
{% endblock %}

noticias/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Proyecto Informatorio</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'assets/favicon.ico' %}"
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">Chaco Innova</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto py-4 py-lg-0">
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="/noticias">Noticias</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="/contacto">
                Contactanos</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="/about"
                >Acerca de</a
              >
            {% if user.is_authenticated %}
            </li>
            <li class="nav-item">
                <a class="nav-link px-lg-3 py-3 py-lg-4" href="/noticias/crear"
                  >Crear noticias</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link px-lg-3 py-3 py-lg-4" href="/logout"
                  >Salir de mi cuenta</a
                >
            {% else %}
              </li>
            <li class="nav-item">
              <a class="nav-link px-lg-3 py-3 py-lg-4" href="/singup"
                >Registrate</a
              >
            </li>
            <li class="nav-item">
                <a class="nav-link px-lg-3 py-3 py-lg-4" href="/singin"
                  >Iniciar sesión</a
                >
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>


{% block content %}

{% endblock content %}

    <!-- Footer-->
    <footer class="border-top">
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <style>
        body {
          padding-top: 100px; 
        }
      </style>
  </body>
</html>

noticias/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'assets/img/chaco.jpg' %}')">

    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Contactanos</h1>
                    <span class="subheading">¿Preguntas? Tengo respuestas.</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>¿Quieres estar en contacto? ¡Completa el formulario debajo y responderé lo más pronto posible!</p>
                <div class="my-5">
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- * * SB Forms Contact Form * *-->
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- This form is pre-integrated with SB Forms.-->
                    <!-- To make this form functional, sign up at-->
                    <!-- https://startbootstrap.com/solution/contact-forms-->
                    <!-- to get an API token!-->
                    <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                        <div class="form-floating">
                            <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                            <label for="name">Name</label>
                            <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                            <label for="email">Email address</label>
                            <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                            <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                            <label for="phone">Phone Number</label>
                            <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                        </div>
                        <div class="form-floating">
                            <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                            <label for="message">Message</label>
                            <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                        </div>
                        <br />
                        <!-- Submit success message-->
                        <!---->
                        <!-- This is what your users will see when the form-->
                        <!-- has successfully submitted-->
                        <div class="d-none" id="submitSuccessMessage">
                            {% if success %}
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">Form submission successful!</div>
                                    Tu mensaje ha sido enviado con éxito. Nos pondremos en contacto contigo pronto.
                                </div>
                            {% endif %}
                        </div>
                        <!-- Submit Button-->
                        <button class="btn btn-primary text-uppercase" id="submitButton" type="submit">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

noticias/templates/crear_noticia.html
<!-- Tu plantilla HTML -->
{% extends "base.html" %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h1 class="text-center mb-4">Crear Noticias</h1>

            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}

            <form action="{% url 'crear_noticia' %}" method="post" enctype="multipart/form-data" class="mb-5">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_titulo" class="form-label">Título</label>
                    {{ form.titulo }}
                </div>
                <div class="mb-3">
                    <label for="id_descripcion" class="form-label">Descripción</label>
                    {{ form.descripcion }}
                </div>
                <div class="mb-3">
                    <label for="id_imagen" class="form-label">Imagen</label>
                    {{ form.imagen }}
                </div>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

noticias/templates/home.html
{% extends 'base.html' %}
{% block content %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('static/assets/img/chaco.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Emprendimientos del Chaco</h1>
                            <span class="subheading">blog de noticias</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post previews of the latest three news -->
                    {% for noticia in ultimas_noticias %}
                    <div class="post-preview">
                        <a href="{% url 'noticia_detalles' noticia.pk %}">
                            <h2 class="post-title">{{ noticia.titulo }}</h2>
                        </a>
                        <p class="post-meta">
                            Creado por
                            <a>{{ noticia.user.username }}</a>
                        </p>
                    </div>
                    <!-- Divider -->
                    {% if not forloop.last %}
                    <hr class="my-4" />
                    {% endif %}
                    {% empty %}
                    <p>No hay noticias disponibles.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4">
                        <a class="btn btn-primary text-uppercase" href="{% url 'noticias' %}">Más Publicaciones →</a>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}

noticias/templates/noticia_detalles.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Page content-->
<div class="container mt-5 content-container">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4 text-center">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{ noticia.titulo }}</h1>
                </header>
                <!-- Preview image figure-->
                <figure class="mb-4 text-center">
                    <!-- Mostrar la imagen de la noticia -->
                    {% if noticia.imagen %}
                    <img class="img-fluid rounded" src="{{ noticia.imagen.url }}" alt="{{ noticia.titulo }}" />
                    {% else %}
                    <img class="img-fluid rounded" src="{% static 'ruta/de/imagen/por/defecto.jpg' %}" alt="Imagen por defecto" />
                    {% endif %}
                    <!-- Botón de editar la noticia -->
                    {% if noticia.user == request.user %}
                    <div style="text-align: right;">
                        <a href="{% url 'noticia_editar' noticia.pk %}" class="btn btn-primary">Editar</a>
                    </div>
                    {% endif %}
                </figure>
                <!-- Post content-->
                <section class="mb-5">
                    <p>{{ noticia.descripcion }}</p>
                    <!-- Post meta content (Usuario y Fecha) -->
                    <div class="text-muted fst-italic mb-2">
                        Publicado por {{ noticia.user.username }} el {{ noticia.fecha }}
                    </div>
                </section>
            </article>

            <!-- Título de comentarios -->
            <h2>Comentarios</h2>

            <!-- Espacio entre formulario de comentario y comentarios -->
            <div style="margin-bottom: 20px;"></div>

            <!-- Comments section-->
            <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">
                        <!-- Comment form -->
                        {% if request.user.is_authenticated %}
                        <form method="POST" action="{% url 'comentarios:agregar' noticia.pk %}">
                            {% csrf_token %}
                            <textarea name="comentario" class="form-control" rows="3" placeholder="¡Únete a la discusión y deja un comentario!"></textarea>
                            <input type="submit" value="COMENTAR" class="btn btn-primary mt-2">
                        </form>
                        {% else %}
                        <p>Para dejar un comentario, por favor <a href="{% url 'singin' %}">inicia sesión</a>.</p>
                        {% endif %}
                        
                        <!-- Espacio adicional entre formulario y comentarios -->
                        <div style="margin-bottom: 20px;"></div>

                        <!-- Comments -->
                        {% for c in comentarios %}
                        <div class="mb-4">
                            <!-- Comment -->
                            <div class="fw-bold">{{ c.usuario }}: {{ c.texto }}</div>
                            {% if request.user == c.usuario %}
                            <a href="{% url 'comentarios:borrar_comentario' c.pk %}">borrar</a> - <a href="{% url 'comentarios:modificar_comentario' c.pk %}">modificar</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

{% endblock content %}

noticias/templates/noticia_editar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Page content-->
<div class="container mt-5 content-container">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4 text-center">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{ noticia.titulo }}</h1>
                </header>

                <!-- Preview image figure-->
                <figure class="mb-4 text-center">
                    <!-- Mostrar la imagen de la noticia -->
                    {% if noticia.imagen %}
                    <img class="img-fluid rounded" src="{{ noticia.imagen.url }}" alt="{{ noticia.titulo }}" />
                    {% else %}
                    <img class="img-fluid rounded" src="{% static 'ruta/de/imagen/por/defecto.jpg' %}" alt="Imagen por defecto" />
                    {% endif %}
                </figure>

                <!-- Post content-->
                <section class="mb-5">
                    <p>{{ noticia.descripcion }}</p>
                    <!-- Post meta content (Usuario y Fecha) -->
                    <div class="text-muted fst-italic mb-2">
                        Publicado por {{ noticia.user.username }} el {{ noticia.fecha }}
                    </div>

                    <!-- Formulario para editar la noticia -->
                    {% if noticia.user == request.user %}
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label for="id_imagen">Imagen:</label>
                        {{ form.imagen }}
                        <br>
                        <label for="id_titulo">Título:</label>
                        {{ form.titulo }}
                        <!-- Otros campos del formulario -->
                        {{ form.descripcion }}
                        <button type="submit" class="btn btn-primary mt-2">Actualizar</button>
                    </form>
                    <form action="{% url 'borrar_noticia' noticia.pk %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger mt-2">Borrar</button>
                    </form>
                    {% endif %}
                </section>
            </article>
        </div>
    </div>
</div>

{% endblock %}

noticias/templates/noticias.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('{% static 'assets/img/chaco.jpg' %}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <h1>Noticias</h1>
                        <h2 class="subheading">Aquí mostramos todas las noticias</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Post Content-->
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for noticia in noticias %}
                        <a href="{% url 'noticia_detalles' noticia.pk %}">
                            <h2>{{ noticia.titulo }}</h2>
                            {% if noticia.imagen %}
                                <img class="img-fluid" src="{{ noticia.imagen.url }}" alt="{{ noticia.titulo }}" />
                            {% else %}
                                <!-- Si no hay imagen asociada, muestra una imagen predeterminada -->
                                <img class="img-fluid" src="{% static 'assets/img/default-image.jpg' %}" alt="Imagen predeterminada" />
                            {% endif %}
                        </a>
                        <p>{{ noticia.descripcion|slice:":200" }}{% if noticia.descripcion|length > 200 %}...{% endif %}</p>
                        <p>{{ noticia.user.username }}</p>
                        <!-- Puedes agregar más detalles de la noticia si es necesario -->
                        
                        <!-- Más contenido de la noticia si es necesario -->

                        <!-- Fin del detalle de la noticia -->
                        <hr>
                    {% endfor %}
                </div>
            </div>
        </div>
    </article>
{% endblock content %}

noticias/templates/singin.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5 d-flex justify-content-center align-items-center">
  <!-- Pills navs -->
  <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
  </ul>
  <!-- Pills navs -->

  <!-- Pills content -->
  <div class="tab-content">
    <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
      <form action="/singin/" method="POST" class="text-center">
        {% csrf_token %}
        {{ form.username.label_tag }}
        <div class="form-outline mb-4">
          <input type="text" id="loginName" name="username" class="form-control" />
        </div>

        {{ form.password.label_tag }}
        <div class="form-outline mb-4">
          <input type="password" id="loginPassword" name="password" class="form-control" />
        </div>

        {% if error %}
          <p style="color: red;">{{ error }}</p>
        {% endif %}

        <div class="d-grid gap-2">
          <button type="submit" class="btn btn-primary btn-block mb-2">Iniciar sesión</button>
          <a href="/singup" class="btn btn-secondary btn-block">Registrate</a>
        </div>
      </form>
    </div>

    <div class="tab-pane fade" id="pills-register" role="tabpanel" aria-labelledby="tab-register">
      <!-- Your register form content here -->
    </div>
  </div>
  <!-- Pills content -->
</div>
{% endblock %}

noticias/templates/singin1.html
{% extends "base.html" %}


{% block content %}
<h1> SINGIN <h1> 

{{error}}

<form action="/singin/" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button>
        Iniciar sesión
    </button>
</form>
{% endblock%}

noticias/templates/singup1.html
{% extends 'base.html' %}

{% block content %}
<h1>Singup</h1>

{{error}}

<form action= "/singup/" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    
    <button>
            Singup
    </button>

</form>

{% endblock %}